services:

  frontend:
    build: ./frontend
    # command: npm run dev -- --host 0.0.0.0 --port 5173

    volumes:
      - frontend_build:/app/dist

  backend:
    build: ./backend
    ports:
      - 8000:8000
    expose:
      - "8000"


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_started

volumes:
  frontend_build:
